name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Test CLI functionality
      run: |
        node dist/cli.js --help
        node dist/cli.js list

    - name: Test package exports
      run: |
        node -e "
        const lib = require('./dist/index.js');
        console.log('✅ Main exports:', Object.keys(lib));
        const { MAVLinkParser } = lib;
        const parser = new MAVLinkParser();
        console.log('✅ Package working correctly');
        "

    - name: Verify generated types
      run: |
        node -e "
        const commonTypes = require('./dist/types/common/index.js');
        console.log('✅ CommonTypes available');
        const minimalTypes = require('./dist/types/minimal/index.js');
        console.log('✅ MinimalTypes available');
        console.log('✅ All generated types accessible');
        "

  build-check:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Check package size
      run: |
        npm pack --dry-run
        echo "Package ready for publishing"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/
        retention-days: 7
